### ISSUE TITLE
[Feature Request] Save files 

### ISSUE THREAD

**Issue by kilon** [omega-gg/MotionBox#10]
Thank you for this amazing app , I love it !

I would like to save a streaming video to a file, do not know if this is already possible. I see that they are saved in cache folder but they do not have names that are easy to identify.

I would like to save playlists with my own filenames as well.

**Comment by 3unjee** [comment]
Hello kilon,

Video downloads is something I would like to add down the road. Unfortunately I have loads of other things to do before. Contributions on that topic are welcome.

What do you mean exactly by "save playlists" ?

**Comment by kilon** [comment]
I dont mind putting my money where my mouth is, so contribution is doable and its fair for you to ask for help but I must warn you me and C++ do not like each other much 💃 

I dont think you understand what I am suggesting. You already download those videos because you have the cache , or else how it would be possible to watch them ?

What I ask is the ability to take this cache file when they become a complete download and easily rename them. Playlist the same, I want to pick the name of their files and their folders by myself so I easily know which is which. This then will make it much easier to say move my playlists from one computer to another. 

I have no idea what you mean by video download because I dont see how the app can allow me to watch videos without downloading them first. So in my mind those dowloads already exist but obviously are not kept around cause are used as temporary files and as a user I have no means to rename unless I go manually inside the folder find which is which and rename them manually.

Is that make more sense now ?

**Comment by 3unjee** [comment]
Yes, technically streaming is downloading, except you don't necessarily keep the entire file at all time. It could be a chunk depending on the seeking position, or you could have the data in memory instead.

Thus, implementing a way to download the entire file and have it saved on the hard drive isn't something trivial. Especially when you consider the fact that you want to keep streaming functional while you download the file.

As for playlists they are currently "saved" under the "playlists" folder. They are just XML files so you could probably copy paste these from one file to the other. As long as you copy paste everything since proper export is not implemented.
