### ISSUE TITLE
Fullscreen mode doesn't correctly overlap taskbar

### ISSUE THREAD

**Issue by tienery** [omega-gg/MotionBox#2]
As suggested in the title, fullscreen mode doesn't overlap the taskbar, which is what you would expect.

![img](http://image.prntscr.com/image/df57039461b049c6b68139f42b9469ed.png)

This means that you have to close the program and start it back up again to return to normal screen view, which is very annoying.

This is happening on Windows 10, I'm not sure about other OSs.

**Comment by 3unjee** [comment]
Hi Luke,

This issue seems to be Windows 10 specific. I haven't got a copy to test it at the moment.
That will have to wait a bit unless you want to submit a patch :-).

This should happen in the showFullScreen function of [WAbstractView](https://github.com/omega-gg/Sky/blob/master/src/SkGui/src/graphicsview/WAbstractView.cpp).

Thank you for the report !

**Comment by 3unjee** [comment]
This should be fixed by this: https://github.com/omega-gg/MotionBox/commit/0de4e9d57799df74da7c8c0c8d20ca8aa9ba24ba
